import type { Metadata } from "next";
import { IBM_Plex_Sans, Barlow } from "next/font/google";
import "./globals.css";

// LOOPLI: heading_font and body_font from the design system are applied here.
// When generating a client site, replace these imports and variable names
// with the fonts specified in the design system JSON.
const bodyFont = IBM_Plex_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const headingFont = Barlow({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Excavator Hire Wollongong",
  description: "Generated by Loopli",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bodyFont.variable} ${headingFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
